---
title: "GIS Coursework"
author: "C T Au"
date: "11/5/2018"
output: pdf_document
---


```{r Loading csv data to RMarkdown}
#Loading 'WorkingHK' csv Data to R
WorkingHK <- read.csv('work.csv')

#Delete unwanted variables, to only show the variable for 'foot'
df <- WorkingHK[ -c(2,3, 5:13) ]
```

```{r Spatial Data}

#Load packages for creating map
library(maptools)
library(RColorBrewer)
library(classInt)
library(sp)
library(rgeos)
library(tmap)
library(tmaptools)
library(sf)
library(rgdal)
library(geojsonio)

#Loading Shapefile of Hong Kong 
HKMapSF <- read_shape('Hong_Kong_18_Districts.shp')
qtm(HKMapSF)
```

Joining attribute table 'df' to the 'HKMapSF' and change map to 'sp'
```{r}
HKDataMap <- append_data(HKMapSF, df, key.shp = "ENAME", key.data = "X...district", ignore.duplicates = TRUE)

class(HKDataMap)
HKDataMapSP <- as(HKDataMap, "Spatial")
class(HKDataMapSP)

```

Plotting a Cartogram
```{r Cartogram}
#refernce cartogram function!
library(cartogram)
HK_sp_cont <- cartogram_cont(HKDataMapSP, "foot", itermax = 20)
tmap_mode("plot")
tm_shape(HK_sp_cont) + 
  tm_polygons("foot", 
        style="jenks",
        palette="Blues",
        title="Workers who commute by foot")+
  tm_layout(main.title = "Cartogram of Workers in Hong Kong \nwho commute by foot in 2016", main.title.position= "center", main.title.size = 1, legend.outside = TRUE, legend.outside.position = c("right", "bottom")) +
  tm_compass(position = c("left", "top"),type = "arrow")

```

Create as an Interactive Map
```{r}
library(shinyjs)
tmap_mode("view")
HK_sp_cont_1 <- HK_sp_cont[ -c(1:2) ]
tm_shape(HK_sp_cont_1) + tm_polygons("foot",style="jenks",palette="Blues",midpoint=NA, title="Cartogram of Hong Kong's \nworkers who commute by foot in 2016", alpha=0.75)
```


